In [2]:
# Librerías necesarias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Cargar los datos
df = pd.read_csv('New_BPD.csv')

df.head()



Age Sex Race      District  Year  Month  DayOfWeek  Hour OffenseCategory  \
0  54.0   M    B  Northeastern  2016     11          5  22.0  Violent Crimes   
1  22.0   M    B  Southwestern  2016     11          5  21.0           Other   
2  46.0   M    A      Southern  2016     11          5  15.0           Other   
3  20.0   M    U  Southeastern  2016     11          5  15.0  Violent Crimes   
4  22.0   M    B  Northeastern  2016     11          5  13.0  Violent Crimes   

    Latitude  Longitude  
0  39.320869 -76.565245  
1  39.281149 -76.682128  
2  39.274378 -76.627630  
3  39.297001 -76.579386  
4  39.333006 -76.545972

In [4]:
# Separación de características y variable objetivo
X = df.drop('Race', axis=1)
y = df['Race']

# Normalización de los datos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Balanceo de datos con SMOTE ajustando el parámetro k_neighbors
smote = SMOTE(k_neighbors=3)
X_resampled, y_resampled = smote.fit_resample(X_scaled, y)

# División del conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Creación y entrenamiento del modelo KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predicción y evaluación del modelo
y_pred = knn.predict(X_test)

# Evaluación del modelo
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))


ValueError: could not convert string to float: 'M'

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Cargar los datos
df = pd.read_csv('BPD_Arrests.csv')

# Seleccionar solo las columnas relevantes y eliminar las innecesarias
df = df[['Age', 'Sex', 'Race']]

# Eliminar filas con valores faltantes
df.dropna(inplace=True)

# Convertir características categóricas en variables dummy
df = pd.get_dummies(df, columns=['Sex'])

# Separación de características y variable objetivo
X = df.drop('Race', axis=1)
y = df['Race']

# Normalización de los datos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Balanceo de datos con SMOTE ajustando el parámetro k_neighbors
smote = SMOTE(k_neighbors=3)
X_resampled, y_resampled = smote.fit_resample(X_scaled, y)

# División del conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Creación y entrenamiento del modelo KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predicción y evaluación del modelo
y_pred = knn.predict(X_test)

# Evaluación del modelo
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))


Matriz de confusión:
 [[10014  4801  3059  2088  1625]
 [ 6560  7033  3097  2226  2262]
 [ 6631  5299  6669  1698  1117]
 [ 6350  5991  4177  2644  2053]
 [ 5680  5623  3307  2667  3957]]

Reporte de clasificación:
               precision    recall  f1-score   support

           A       0.28      0.46      0.35     21587
           B       0.24      0.33      0.28     21178
           I       0.33      0.31      0.32     21414
           U       0.23      0.12      0.16     21215
           W       0.36      0.19      0.25     21234

    accuracy                           0.28    106628
   macro avg       0.29      0.28      0.27    106628
weighted avg       0.29      0.28      0.27    106628



In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Cargar los datos
df = pd.read_csv('New_BPD.csv')

# Eliminar filas con valores faltantes
df.dropna(inplace=True)

# Convertir características categóricas en variables dummy
df = pd.get_dummies(df)

# Separación de características y variable objetivo
X = df.drop('Race')
y = df['Race']

# Normalización de los datos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Balanceo de datos con SMOTE ajustando el parámetro k_neighbors
smote = SMOTE(k_neighbors=3)
X_resampled, y_resampled = smote.fit_resample(X_scaled, y)

# División del conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Creación y entrenamiento del modelo KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predicción y evaluación del modelo
y_pred = knn.predict(X_test)

# Evaluación del modelo
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))


KeyError: "['Race'] not found in axis"